name: algo-appliquee-binder-environment
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - ipyparallel
  - ipython
  - ipywidgets      # Jupyter dependency
  - matplotlib      # Famous plotting library
  - networkx        # Graph library
  - numpy           # Famous hardware accelerated array processing library
  - scikit-image    # Image processing (good friend of numpy)
  - sympy           # Computer Algebra System (CAS) for symbolic mathematics
  - toolz           # Basic extensions & algorithms for basic Python collections