@startuml

state Bloc1
state Bloc2
state Bloc3
state Bloc4
state Bloc5
state Bloc6
state ChoixException <<choice>>

[*]             --> Bloc1

Bloc1           --> ChoixException  : exception\nlevée

ChoixException  --> Bloc2           : Erreur
ChoixException  --> Bloc3           : AutreErreur\nou\nPasDeBol
ChoixException  --> Bloc4           : autre exception\nnon listée

Bloc1           --> Bloc5           : aucune\nexception

Bloc2           --> Bloc6
Bloc3           --> Bloc6
Bloc4           --> Bloc6
Bloc5           --> Bloc6

Bloc6           --> [*]

@enduml